#!/usr/bin/env python
import csv
import json
import re
import sys

jam_ok = '--no-jam' not in sys.argv
compo_ok = '--no-compo' not in sys.argv
text_filter = None

for i, arg in enumerate(sys.argv):
    if arg == '--text':
        text_filter = sys.argv[i + 1]

re_cache = None
with open('infos.json', 'r') as f:
    writer = csv.writer(sys.stdout)
    for info in json.load(f)['infos']:
        if info["subsubtype"] == 'jam' and not jam_ok:
            continue
        if info["subsubtype"] == 'compo' and not compo_ok:
            continue

        if text_filter is not None:
            if re_cache is None:
                re_cache = re.compile(text_filter)
            if not re_cache.search(info["body"].lower()):
                continue

        url = "https://ldjam.com" + info["path"]
        writer.writerow((info["name"], url))
